//
// BaseProtocol.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import KakaJSON

//class BaseModel: ModelProtocol {
//    required init() { }
//}

protocol ModelProtocol: Convertible, Encodable {}
protocol ModelEnumProtocol: ConvertibleEnum, Encodable {}

extension ModelProtocol {
    public func kj_modelKey(from property: Property) -> ModelPropertyKey {
        switch property.name {
        case "weatherDescription":
            // API返"weatherDescription", Model出"description"
            return "description"
        default:
            return property.name
        }
    }
}
